import {
  AirJordanMid,
  AirJordanMid1,
  AirJordanMid2,
  AirJordanMid3,
  AirJordanRetro4,
  AirJordanRetro41,
  AirJordanRetro42,
  AirJordanRetro43,
  AirJordanRetro6,
  AirJordanRetro61,
  AirJordanRetro62,
  AirJordanRetro63,
  AirJordanRetro13,
  AirJordanRetro131,
  AirJordanRetro132,
  AirJordanRetro133,
  CurlyJacket,
  CurlyJacket1,
  CurlyJacketVid,
  GRAINLEATHER,
  GRAINLEATHER1,
  GRAINLEATHERVid,
  JordanSpizike,
  JordanSpizike1,
  JordanSpizike2,
  JordanSpizike3,
  EVENINGDRESS,
  EVENINGDRESS1,
  EVENINGDRESSVid,
  LEATHERJACKET,
  LEATHERJACKET1,
  LEATHERJACKETVid,
  SOFTSILKKAFTAN,
  SOFTSILKKAFTAN1,
  SOFTSILKKAFTANVid,
  VISCOSESATIN,
  VISCOSESATIN1,
  VISCOSESATINVid,
} from "../assets/New Arrivals";

import {
  CADYSILKMAROCAINE,
  CADYSILKMAROCAINE1,
  CADYSILKMAROCAINEVid,
  DOUBLEGEORGETTESTRETCH,
  DOUBLEGEORGETTESTRETCHVid,
  DOUBLEGEORGETTESTRETCH1,
  DOUBLESILKGEORGETTE,
  DOUBLESILKGEORGETTE1,
  DOUBLESILKGEORGETTE2,
  DOUBLESILKGEORGETTEVid,
  DOUBLESILKGEORGETTESTRAPLESS,
  DOUBLESILKGEORGETTESTRAPLESS1,
  DOUBLESILKGEORGETTESTRAPLESSVid,
  FAUXLEATHERRUCHED,
  FAUXLEATHERRUCHED1,
  FAUXLEATHERRUCHEDVid,
  FINECASHMERESILK,
  FINECASHMERESILK1,
  FINECASHMERESILKVid,
  HALTERNECKEVENINGDRESS,
  HALTERNECKEVENINGDRESS1,
  HALTERNECKEVENINGDRESSVid,
  HALTERNECKJERSEY,
  HALTERNECKJERSEY1,
  HALTERNECKJERSEYVid,
  HONEYCOMBVISCOSEJERSEY,
  HONEYCOMBVISCOSEJERSEY1,
  JERSEYHALTERNECKKNIT,
  JERSEYHALTERNECKKNIT1,
  JERSEYHALTERNECKKNITVid,
  LUREXJERSEYKNIT,
  LUREXJERSEYKNITVid,
  LUREXKNITEVENING,
  LUREXKNITEVENING1,
  LUREXKNITEVENINGVid,
  OPENBACKKNIT,
  OPENBACKKNITVid,
  OPENBACKKNIT1,
  OPENBACKEVENINGDRESS,
  OPENBACKEVENINGDRESSVid,
  OPENBACKEVENINGDRESS1,
  OPENWORKKNITHALTERNECK,
  OPENWORKKNITHALTERNECK1,
  OPENWORKKNITHALTERNECKVid,
  OPENWORKLUREX,
  OPENWORKLUREX1,
  OPENWORKLUREXVid,
  OPENWORKLUREXSCOOP,
  OPENWORKLUREXSCOOP1,
  OPENWORKLUREXSCOOPVid,
  OPENWORKMAXIDRESS,
  OPENWORKMAXIDRESS1,
  OPENWORKSTRETCHVISCOSE,
  OPENWORKSTRETCHVISCOSE1,
  OPENWORKMAXIDRESS2,
  OPENWORKSTRETCHVISCOSEVid,
  SABLEHALTERNECK,
  SABLEHALTERNECK1,
  SILKCREPECHIFFON,
  SILKCREPECHIFFON1,
  SILKCREPECHIFFONVid,
  SLINKYVISCOSEJERSEY,
  SLINKYVISCOSEJERSEYVid,
  SLINKYVISCOSEJERSEY1,
  STRETCHSABLESTRAPLESS,
  STRETCHSABLESTRAPLESS1,
  STRETCHSABLESTRAPLESSVid,
  VELVETSTRAPLESS,
  VELVETSTRAPLESS1,
  VELVETSTRAPLESSVid,
  WOOLBLENDTWEED,
  WOOLBLENDTWEED1,
  WOOLBLENDTWEEDVid,
} from "../assets/dresses";
const products = {
  newArrivals: [
    {
      id: 1,
      name: "Air Jordan 13 Retro 'Dune Red'",
      mainImage: AirJordanRetro13,
      subImages: [AirJordanRetro131, AirJordanRetro132, AirJordanRetro133],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 200,
      description:
        "The Air Jordan 13 Retro brings back the stealthy, shrouded design with a fresh mix of colors and textures. Crafted to the '98 specs as designed by Tinker Hatfield, you're getting the panther paw outsole, the holographic eye, and everything else that made these kicks iconic in the first place. MJ rode the original AJ13 all the way to his 6th ring—how are you gonna make this edition famous?",
      category: "men",
      stock: 10,
    },
    {
      id: 2,
      name: "Jordan Spizike Low",
      mainImage: JordanSpizike,
      subImages: [JordanSpizike1, JordanSpizike2, JordanSpizike3],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 160,
      description:
        "The Spizike takes elements of five classic Jordans, combines them, and gives you one iconic sneaker. It's an homage to Spike Lee formally introducing Hollywood and hoops in a culture moment. You get a great looking pair of kicks with some history. What more can you ask for? Ya dig?",
      category: "men",
      stock: 10,
    },
    {
      id: 3,
      name: "JoAir Jordan 4 Retro 'Oxidized Green'",
      mainImage: AirJordanRetro4,
      subImages: [AirJordanRetro41, AirJordanRetro42, AirJordanRetro43],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 215,
      description:
        "Step into a classic. This AJ4 throws it back with full-grain and synthetic leathers and premium textiles. Lush colors and metallic pops update the icon, while original design elements—like floating eyestays and mesh-inspired accents—feel just as fresh as they did in '89.",
      category: "men",
      stock: 10,
    },
    {
      id: 4,
      name: `Air Jordan 6 Retro "White & Black"`,
      mainImage: AirJordanRetro6,
      subImages: [AirJordanRetro61, AirJordanRetro62, AirJordanRetro63],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 200,
      category: "men",
      description:
        "MJ wore 'em when he claimed his first championship and you'll be wearing 'em for—well, whatever you want. Laden with dynamic design lines and those iconic lace locks, these sneakers bring throwback style to any 'fit. Lace up, and let your kicks do the talking.",
      stock: 10,
    },
    {
      id: 5,
      name: `Air Jordan 1 Mid`,
      mainImage: AirJordanMid,
      subImages: [AirJordanMid1, AirJordanMid2, AirJordanMid3],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 110,
      category: "men",
      description:
        "This iteration of the AJ1 reimagines Mike's first signature model with a fresh mix of colors. Premium materials, soft cushioning and a padded ankle collar offer total support and celebrate the shoe that started it all.",
      stock: 10,
    },
    {
      id: 6,
      name: "VISCOSE SATIN STRETCH JERSEY KAFTAN",
      mainImage: VISCOSESATIN,
      subImages: [VISCOSESATIN1],
      subVideos: [VISCOSESATINVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4790,
      description:
        "Discover refined style with the Asymmetric Kaftan. The crewneck design includes a drop opening on the back, adorned with a jewel button for an exquisite finish. Crafted from soft silk stretch cady, this kaftan offers an elegant drape and a hint of stretch. The luxurious fabric composition of 94% silk and 6% elastane ensures a comfortable yet sophisticated fit, perfect for any occasion.",
      category: "women",
      stock: 15,
    },

    {
      id: 8,
      name: "SOFT SILK STRETCH CADY KAFTAN",
      mainImage: SOFTSILKKAFTAN,
      subImages: [SOFTSILKKAFTAN1],
      subVideos: [SOFTSILKKAFTANVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 5290,
      description:
        "Discover refined style with the Asymmetric Kaftan. The crewneck design includes a drop opening on the back, adorned with a jewel button for an exquisite finish. Crafted from soft silk stretch cady, this kaftan offers an elegant drape and a hint of stretch. The luxurious fabric composition of 94% silk and 6% elastane ensures a comfortable yet sophisticated fit, perfect for any occasion.",
      category: "women",
      stock: 15,
    },
    {
      id: 9,
      name: "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS",
      mainImage: EVENINGDRESS,
      subImages: [EVENINGDRESS1],
      subVideos: [EVENINGDRESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4590,
      description:
        "Make a statement in the Halterneck Evening Dress. This full-length gown features a striking front criss-cross detail and a draping effect that exudes glamour. Side mesh inserts add a modern touch, while the open back creates an alluring silhouette. An invisible zip and hook-and-eye fastening ensure a smooth finish. Crafted from fluid knitted viscose stretch jersey, this dress is both comfortable and elegant, made from 97% viscose and 3% elastane for a perfect fit.",
      category: "women",
      stock: 15,
    },
    {
      id: 10,
      name: "CURLY SHEARLING JACKET",
      mainImage: CurlyJacket,
      subImages: [CurlyJacket1, CurlyJacketVid],
      subVideos: [CurlyJacketVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "jackets",
      price: 4980,
      description:
        "Stay cozy and chic with the Shearling Jacket. This luxurious piece features a hook-and-eye closure and slight padding for added comfort. Fully lined and crafted from curly shearling, it promises warmth and style. Made from 100% lamb fur, this jacket is perfect for those cold days when you still want to look your best.",
      category: "women",
      stock: 15,
    },
    {
      id: 11,
      name: "CURLY SHEARLING SHEARLING & LEATHER WESTERN JACKET",
      mainImage: LEATHERJACKET,
      subImages: [LEATHERJACKET1],
      subVideos: [LEATHERJACKETVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "jackets",
      price: 6890,
      description:
        "Channel rugged sophistication with the Shearling Western Jacket. Featuring Tom Ford's signature press snap fastening along the front closure, pockets, and cuffs, this jacket is both functional and stylish. Patch flap chest pockets and side pockets provide ample storage, while the Tom Ford signature leather grab handle adds a distinctive touch. Tonal hardware and slight padding ensure comfort and durability. Fully lined and crafted from soft shearling and new plonge leather, this jacket is 100% lamb fur, offering unparalleled warmth and luxury.",
      category: "women",
      stock: 15,
    },
    {
      id: 12,
      name: "GRAIN LEATHER TARA MEDIUM CROSSBODY",
      mainImage: GRAINLEATHER,
      subImages: [GRAINLEATHER1],
      subVideos: [GRAINLEATHERVid],
      sizes: [],
      colors: ["black", "champaigne"],
      type: "bags",
      price: 2290,
      description:
        "Elevate your accessory game with the Hanging T Signature Hardware Bag. Featuring an adjustable shoulder strap, this versatile bag can be worn over the shoulder or as a crossbody. The magnetic closure ensures easy access, while the single compartment and inside zipped pocket provide ample storage. An outer flat pocket offers additional space for essentials. The bag is lined with microfiber for a soft touch, and crafted from 100% calfskin for a luxurious feel. Measuring 26 x 26 x 9.5 cm with a medium strap drop of 46 cm, this bag is the perfect blend of functionality and style.",
      category: "women",
      stock: 15,
    },

    // Add more products as needed
  ],
  men: [
    {
      id: 1,
      name: "Air Jordan 13 Retro 'Dune Red'",
      mainImage: AirJordanRetro13,
      subImages: [AirJordanRetro131, AirJordanRetro132, AirJordanRetro133],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 200,
      description:
        "The Air Jordan 13 Retro brings back the stealthy, shrouded design with a fresh mix of colors and textures. Crafted to the '98 specs as designed by Tinker Hatfield, you're getting the panther paw outsole, the holographic eye, and everything else that made these kicks iconic in the first place. MJ rode the original AJ13 all the way to his 6th ring—how are you gonna make this edition famous?",
      category: "men",
      stock: 10,
    },
    {
      id: 2,
      name: "Jordan Spizike Low",
      mainImage: JordanSpizike,
      subImages: [JordanSpizike1, JordanSpizike2, JordanSpizike3],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 160,
      description:
        "The Spizike takes elements of five classic Jordans, combines them, and gives you one iconic sneaker. It's an homage to Spike Lee formally introducing Hollywood and hoops in a culture moment. You get a great looking pair of kicks with some history. What more can you ask for? Ya dig?",
      category: "men",
      stock: 10,
    },
    {
      id: 3,
      name: "JoAir Jordan 4 Retro 'Oxidized Green'",
      mainImage: AirJordanRetro4,
      subImages: [AirJordanRetro41, AirJordanRetro42, AirJordanRetro43],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 215,
      description:
        "Step into a classic. This AJ4 throws it back with full-grain and synthetic leathers and premium textiles. Lush colors and metallic pops update the icon, while original design elements—like floating eyestays and mesh-inspired accents—feel just as fresh as they did in '89.",
      category: "men",
      stock: 10,
    },
    {
      id: 4,
      name: `Air Jordan 6 Retro "White & Black"`,
      mainImage: AirJordanRetro6,
      subImages: [AirJordanRetro61, AirJordanRetro62, AirJordanRetro63],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 200,
      category: "men",
      description:
        "MJ wore 'em when he claimed his first championship and you'll be wearing 'em for—well, whatever you want. Laden with dynamic design lines and those iconic lace locks, these sneakers bring throwback style to any 'fit. Lace up, and let your kicks do the talking.",
      stock: 10,
    },
    {
      id: 5,
      name: `Air Jordan 1 Mid`,
      mainImage: AirJordanMid,
      subImages: [AirJordanMid1, AirJordanMid2, AirJordanMid3],
      subVideos: [],
      sizes: [8, 9, 10, 11, 12],
      type: "shoes",
      price: 110,
      category: "men",
      description:
        "This iteration of the AJ1 reimagines Mike's first signature model with a fresh mix of colors. Premium materials, soft cushioning and a padded ankle collar offer total support and celebrate the shoe that started it all.",
      stock: 10,
    },
    // Add more products as needed
  ],
  women: [
    {
      id: 6,
      name: "VISCOSE SATIN STRETCH JERSEY KAFTAN",
      mainImage: VISCOSESATIN,
      subImages: [VISCOSESATIN1],
      subVideos: [VISCOSESATINVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4790,
      description:
        "Discover refined style with the Asymmetric Kaftan. The crewneck design includes a drop opening on the back, adorned with a jewel button for an exquisite finish. Crafted from soft silk stretch cady, this kaftan offers an elegant drape and a hint of stretch. The luxurious fabric composition of 94% silk and 6% elastane ensures a comfortable yet sophisticated fit, perfect for any occasion.",
      category: "women",
      stock: 15,
    },

    {
      id: 8,
      name: "SOFT SILK STRETCH CADY KAFTAN",
      mainImage: SOFTSILKKAFTAN,
      subImages: [SOFTSILKKAFTAN1],
      subVideos: [SOFTSILKKAFTANVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 5290,
      description:
        "Discover refined style with the Asymmetric Kaftan. The crewneck design includes a drop opening on the back, adorned with a jewel button for an exquisite finish. Crafted from soft silk stretch cady, this kaftan offers an elegant drape and a hint of stretch. The luxurious fabric composition of 94% silk and 6% elastane ensures a comfortable yet sophisticated fit, perfect for any occasion.",
      category: "women",
      stock: 15,
    },
    {
      id: 9,
      name: "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS",
      mainImage: EVENINGDRESS,
      subImages: [EVENINGDRESS1],
      subVideos: [EVENINGDRESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4590,
      description:
        "Make a statement in the Halterneck Evening Dress. This full-length gown features a striking front criss-cross detail and a draping effect that exudes glamour. Side mesh inserts add a modern touch, while the open back creates an alluring silhouette. An invisible zip and hook-and-eye fastening ensure a smooth finish. Crafted from fluid knitted viscose stretch jersey, this dress is both comfortable and elegant, made from 97% viscose and 3% elastane for a perfect fit.",
      category: "women",
      stock: 15,
    },
    {
      id: 10,
      name: "CURLY SHEARLING JACKET",
      mainImage: CurlyJacket,
      subImages: [CurlyJacket1, CurlyJacketVid],
      subVideos: [CurlyJacketVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "jackets",
      price: 4980,
      description:
        "Stay cozy and chic with the Shearling Jacket. This luxurious piece features a hook-and-eye closure and slight padding for added comfort. Fully lined and crafted from curly shearling, it promises warmth and style. Made from 100% lamb fur, this jacket is perfect for those cold days when you still want to look your best.",
      category: "women",
      stock: 15,
    },
    {
      id: 11,
      name: "CURLY SHEARLING SHEARLING & LEATHER WESTERN JACKET",
      mainImage: LEATHERJACKET,
      subImages: [LEATHERJACKET1],
      subVideos: [LEATHERJACKETVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "jackets",
      price: 6890,
      description:
        "Channel rugged sophistication with the Shearling Western Jacket. Featuring Tom Ford's signature press snap fastening along the front closure, pockets, and cuffs, this jacket is both functional and stylish. Patch flap chest pockets and side pockets provide ample storage, while the Tom Ford signature leather grab handle adds a distinctive touch. Tonal hardware and slight padding ensure comfort and durability. Fully lined and crafted from soft shearling and new plonge leather, this jacket is 100% lamb fur, offering unparalleled warmth and luxury.",
      category: "women",
      stock: 15,
    },
    {
      id: 12,
      name: "GRAIN LEATHER TARA MEDIUM CROSSBODY",
      mainImage: GRAINLEATHER,
      subImages: [GRAINLEATHER1],
      subVideos: [GRAINLEATHERVid],
      sizes: [],
      colors: ["black", "champaigne"],
      type: "bags",
      price: 2290,
      description:
        "Elevate your accessory game with the Hanging T Signature Hardware Bag. Featuring an adjustable shoulder strap, this versatile bag can be worn over the shoulder or as a crossbody. The magnetic closure ensures easy access, while the single compartment and inside zipped pocket provide ample storage. An outer flat pocket offers additional space for essentials. The bag is lined with microfiber for a soft touch, and crafted from 100% calfskin for a luxurious feel. Measuring 26 x 26 x 9.5 cm with a medium strap drop of 46 cm, this bag is the perfect blend of functionality and style.",
      category: "women",
      stock: 15,
    },
    {
      id: 7,
      name: "CADY SILK MAROCAINE ASYMMETRIC DRESS",
      mainImage: CADYSILKMAROCAINE,
      subImages: [CADYSILKMAROCAINE1],
      subVideos: [CADYSILKMAROCAINEVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4790,
      description:
        "This exquisite piece is an archive item from Tom Ford's Fall/Winter 2018 Pre Collection, showcasing the brand's unparalleled craftsmanship and attention to detail. Crafted from luxurious Cady Silk Marocaine, a fine silk fabric known for its smooth texture and sheen, this garment exudes elegance and sophistication. The design features a below-the-knee length, perfect for those seeking a touch of glamour in their wardrobe.The crew neck and asymmetric long sleeves with zipped cuffs add a modern twist to the classic silhouette, while the center back invisible zip ensures a seamless fit. A unique feature is the center back slit, which adds a playful element to the otherwise refined design. Fully lined for comfort and durability, this piece carries the internal Tom Ford Archive label, certifying its authenticity and exclusivity.Made entirely from 100% silk, this garment combines luxury with functionality, offering a blend of style and comfort. Whether worn for special occasions or as a statement piece in everyday wear, this Tom Ford archive piece is a testament to the brand's commitment to quality and timeless design.",
      category: "women",
      stock: 15,
    },

    {
      id: 14,
      name: "DOUBLE GEORGETTE STRETCH KAFTAN",
      mainImage: DOUBLEGEORGETTESTRETCH,
      subImages: [DOUBLEGEORGETTESTRETCH1],
      subVideos: [DOUBLEGEORGETTESTRETCHVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 8950,
      description:
        "This full-length kaftan is a masterpiece of design, blending elegance with comfort. Featuring a crewneck with a drop opening, it offers a flattering V-neck effect that enhances its allure. The maxi batwing sleeves add a touch of drama, cascading gracefully down the arms for a sophisticated yet relaxed look. Crafted from double georgette stretch, this fabric provides both a soft drape and flexibility, ensuring ease of movement. Made from 94% silk and 6% elastane, it combines the luxurious feel of silk with the added benefit of stretch, making it perfect for all-day wear. This kaftan is a testament to understated luxury, ideal for those who appreciate the finer things in life.",
      category: "women",
      stock: 15,
    },
    {
      id: 15,
      name: "DOUBLE SILK GEORGETTE EVENING DRESS",
      mainImage: DOUBLESILKGEORGETTE,
      subImages: [DOUBLESILKGEORGETTE1, DOUBLESILKGEORGETTE2],
      subVideos: [DOUBLESILKGEORGETTEVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4980,
      category: "women",
      description:
        "This stunning archive piece from Tom Ford's Fall/Winter 2012 Main Collection is a testament to the designer's mastery of eveningwear elegance. A full-length evening dress, it features shaped cap sleeves adorned with shoulder pads, adding a bold, retro flair to its sleek silhouette. The front ruched effect creates a dramatic visual impact, enhancing the dress's allure. Crafted from double silk georgette, this fabric offers a luxurious sheen and soft drape, ensuring the dress moves beautifully with the wearer. The centre back invisible zip and deep slit offer both convenience and a hint of seductive mystery. Small mother of pearl buttons allow for the attachment of a detachable cape (sold separately), providing versatility and an extra layer of sophistication. Fully lined for comfort and structure, this dress carries the internal Tom Ford Archive label, guaranteeing its authenticity and exclusivity. Made entirely from 100% silk, it promises both luxury and timeless appeal, making it a perfect choice for those special occasions where only the finest will do.",
      stock: 15,
    },
    {
      id: 16,
      name: "DOUBLE SILK GEORGETTE STRAPLESS EVENING DRESS",
      mainImage: DOUBLESILKGEORGETTESTRAPLESS,
      subImages: [DOUBLESILKGEORGETTESTRAPLESS1],
      subVideos: [DOUBLESILKGEORGETTESTRAPLESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 6490,
      category: "women",
      description:
        "This archival gem from Tom Ford's Fall/Winter 2015 Main Collection is a quintessential example of elegant evening attire. The strapless evening dress boasts a tonal cotton velvet ribbon at the neckline, complemented by a center back bow, adding a delicate yet sophisticated accent. The low cowl back with a draping effect creates a captivating silhouette, emphasizing the dress's fluidity and grace. Side slits enhance the movement of the dress, allowing for a graceful stride. Crafted meticulously from double silk georgette, this fabric choice ensures a luxurious sheen and a soft, ethereal drape, making the dress both comfortable and visually striking. The dress is made entirely from 100% silk, underscoring its premium quality and timeless appeal. Carrying the internal Tom Ford Archive label, this piece guarantees authenticity and marks it as a rare find for discerning collectors and fashion enthusiasts alike.",
      stock: 15,
    },
    {
      id: 17,
      name: "FAUX LEATHER RUCHED DRESS",
      mainImage: FAUXLEATHERRUCHED,
      subImages: [FAUXLEATHERRUCHED1],
      subVideos: [FAUXLEATHERRUCHEDVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 3790,
      description:
        "Drawing inspiration from an iconic archive piece from Tom Ford's Spring/Summer 2019 Main Collection, this faux leather below-the-knee dress is a contemporary tribute to timeless elegance. The fitted silhouette contours gracefully to the body, emphasizing its sleek and sophisticated design. A mock neck adds a subtle edge, while the diagonal draped panel on top introduces a dynamic play of textures and shapes. The long sleeve with zipped cuffs offers a nod to the collection's original details, ensuring a modern and chic finish. The skirt features ruched fixed sides, creating a flattering A-line shape that flares out elegantly from the waist. Crafted with a center back and side invisible zip for easy wearability, this dress is fully lined for comfort and durability. Bearing the internal Tom Ford Archive label, it stands as a testament to the brand's commitment to quality and innovation. Made from 100% viscose, the faux leather material offers a luxurious matte finish, combining the allure of leather with the softness and drape of viscose. This dress is a celebration of modern femininity, perfect for those who appreciate the fusion of vintage inspiration with contemporary design.",
      stock: 15,
      category: "women",
    },
    {
      id: 18,
      name: "FINE CASHMERE SILK & SILK THREAD DRESS",
      mainImage: FINECASHMERESILK,
      subImages: [FINECASHMERESILK1],
      subVideos: [FINECASHMERESILKVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 2890,
      description:
        "This exquisite archive piece from Tom Ford's Spring/Summer 2018 Pre Collection is a masterful blend of luxury and craftsmanship. The long-sleeved knitted dress, featuring a sheer neckline and shoulders, exudes a sense of sophistication and allure. Its below-the-knee length is perfectly balanced, offering a touch of modesty while still maintaining an air of elegance. Crafted with meticulous attention to detail, the dress includes a center back invisible zip for ease of wear, ensuring a flawless fit. Bearing the internal Tom Ford Archive label, this piece is a testament to the brand's dedication to quality and exclusivity. The dress is crafted from a luxurious combination of fine cashmere silk and silk thread, utilizing a gauge of 14GG and 18GG for unmatched softness and durability. This selection of materials and techniques results in a garment that is not only beautiful but also incredibly comfortable, making it an ideal choice for those special occasions where only the finest will suffice.",
      stock: 15,
      category: "women",
    },
    {
      id: 19,
      name: "HALTERNECK EVENING DRESS WITH EMBROIDERY",
      mainImage: HALTERNECKEVENINGDRESS,
      subImages: [HALTERNECKEVENINGDRESS1],
      subVideos: [HALTERNECKEVENINGDRESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 5290,
      description:
        "This halterneck evening dress is a vision of elegance and intricacy, designed to captivate and charm. With its full-length silhouette, it offers a regal presence, perfect for grand occasions. The dress is meticulously crafted from silk chiffon, a fabric renowned for its lightness and flow, ensuring the gown moves with grace and ethereal beauty. The standout feature is the fully embroidered collar, which combines tonal square beads, cut bugles, and faceted beads, creating a dazzling display of texture and sparkle. This intricate embroidery not only adds a luxurious touch but also serves as a focal point, elevating the overall aesthetic of the dress. Made entirely from 100% silk, the base fabric contributes to the dress's luxurious feel and softness against the skin. The embroidery is composed of 60% polyester and 40% glass, blending durability with the shimmering effect of glass beads for a truly opulent finish. This halterneck evening dress is a testament to exceptional craftsmanship and design, making it an ideal choice for those seeking a statement piece for special events.",
      stock: 15,
      category: "women",
    },
    {
      id: 20,
      name: "HALTERNECK JERSEY EVENING DRESS",
      mainImage: HALTERNECKJERSEY,
      subImages: [HALTERNECKJERSEY1],
      subVideos: [HALTERNECKJERSEYVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 8890,
      description:
        "This halterneck evening dress is a masterpiece of design and craftsmanship, embodying sophistication and allure. Its full-length silhouette is both majestic and timeless, making it an ideal choice for grand occasions. The dress features a daring front cut-out detail, which adds a touch of modernity and intrigue to its classic form. An open back further enhances its seductive appeal, while the muse chain along the neckline and back straps adds a distinctive, vintage-inspired elegance. A center back pleated detail introduces a playful element to the dress's structured design, and the skirt finishes with a short, elegant train, ensuring a memorable entrance. Crafted with a center back invisible zip for ease of wear, the dress is meticulously finished with amber vintage gold metal hardware, lending it a luxurious and exclusive touch. Fully lined in self for comfort and structure, this halterneck evening dress is made from stretch sable' jersey, a blend of 83% viscose, 11% nylon, and 6% elastane. This combination of materials offers both flexibility and a luxurious sheen, making the dress not only beautiful but also incredibly comfortable to wear.",
      stock: 15,
      category: "women",
    },
    {
      id: 21,
      name: "HONEYCOMB VISCOSE JERSEY HALTERNECK EVENING DRESS",
      mainImage: HONEYCOMBVISCOSEJERSEY,
      subImages: [HONEYCOMBVISCOSEJERSEY1],
      subVideos: [],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4290,
      description:
        "This halterneck evening dress is a stunning creation that marries elegance with bold design elements, making it a standout choice for special occasions. Its full-length silhouette commands attention, while the front and back cut-out detail adds a provocative edge, transforming the traditional halterneck into a modern masterpiece. The side draping effect at the waist introduces a dynamic play of lines and shadows, enhancing the dress's fluidity and grace. A center front slit allows for a glimpse of the leg, adding to the dress's allure, and an invisible zip at the center back ensures a seamless fit. Crafted with a stretch internal body for a flattering fit, this dress is meticulously made from honeycomb viscose jersey, a fabric that offers both comfort and a luxurious sheen. The composition of 58% viscose and 42% polyester ensures durability and a soft, breathable feel, making the dress not only a feast for the eyes but also a pleasure to wear. This halterneck evening dress is a testament to innovative design and superior craftsmanship, making it an ideal choice for those who desire a dress that makes a statement.",
      stock: 15,
      category: "women",
    },
    {
      id: 22,
      name: "JERSEY HALTERNECK KNIT EVENING DRESS",
      mainImage: JERSEYHALTERNECKKNIT,
      subImages: [JERSEYHALTERNECKKNIT1],
      subVideos: [JERSEYHALTERNECKKNITVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4290,
      description:
        "This halterneck knitted evening dress is a symphony of elegance and sophistication, designed to capture the essence of glamour and allure. Its full-length silhouette is both regal and timeless, making it an impeccable choice for grand occasions. The open back, enhanced with an adjustable leather strap detail and metal interlocking hardware fastening, offers a daring yet refined contrast to the dress's classic form. A deep side slit adds a flirtatious touch, allowing for a glimpse of the leg, while the amber vintage gold metal hardware lends the dress an exclusive and luxurious finish. Crafted from slinky viscose jersey, this fabric choice ensures the dress flows with grace and offers a soft, luxurious feel against the skin. The dress is made with a gauge of 14, emphasizing its fine knit and the intricate detailing that goes into its construction. Composed entirely of 100% viscose, the dress combines the natural breathability of viscose with its inherent sheen, resulting in a garment that is not only stunning but also incredibly comfortable to wear. This halterneck knitted evening dress is a testament to exceptional craftsmanship and design, making it an ideal choice for those seeking a dress that embodies both sophistication and boldness.",
      stock: 15,
      category: "women",
    },
    {
      id: 23,
      name: "LUREX JERSEY KNIT EVENING DRESS",
      mainImage: LUREXJERSEYKNIT,
      subImages: [],
      subVideos: [LUREXJERSEYKNITVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 2390,
      description:
        "This long-sleeve evening dress features a crewneck with a front cut-out, shoulder pads for a structured look, and a hook and eye neck closure for a secure fit. Crafted from lurex jersey with a gauge of 18, it combines 66% polyester with 34% metalized fibers, offering a blend of durability and a reflective, glamorous finish.",
      stock: 15,
      category: "women",
    },
    {
      id: 24,
      name: "LUREX KNIT EVENING DRESS",
      mainImage: LUREXKNITEVENING,
      subImages: [LUREXKNITEVENING1],
      subVideos: [LUREXKNITEVENINGVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 3250,
      description:
        "This long-sleeve knitted evening dress is full length with a deep V-neck featuring a front teardrop opening. It's crafted from tuck stitch lurex with a gauge of 14, consisting of 57% viscose, 28% polyester, and 15% metallic fiber, offering a luxurious sheen and soft drape.",
      stock: 15,
      category: "women",
    },
    {
      id: 25,
      name: "OPEN BACK KNIT EVENING DRESS",
      mainImage: OPENBACKKNIT,
      subImages: [OPENBACKKNIT1],
      subVideos: [OPENBACKKNITVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 3390,
      description:
        "This long-sleeve knitted evening dress features a turtle neck with a center back buttoned closure, is full length, and has an open back. It's crafted from metal viscose rib with a gauge of 3, consisting of 73% viscose, 14% metallic fiber, and 13% paper, offering a unique blend of texture and shine.",
      stock: 15,
      category: "women",
    },
    {
      id: 26,
      name: "OPEN-BACK KNIT EVENING DRESS",
      mainImage: OPENBACKEVENINGDRESS,
      subImages: [OPENBACKEVENINGDRESS1],
      subVideos: [OPENBACKEVENINGDRESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 2190,
      description:
        "This scoop neck knitted evening dress includes a front side slit and an open back. It's crafted from lurex and viscose jersey with a gauge of 14, made up of 57% viscose, 28% polyester, and 15% metalized polyester, combining a luxurious sheen with softness and drape.",
      stock: 15,
      category: "women",
    },
    {
      id: 27,
      name: "OPENWORK KNIT HALTERNECK EVENING DRESS",
      mainImage: OPENWORKKNITHALTERNECK,
      subImages: [OPENWORKKNITHALTERNECK1],
      subVideos: [OPENWORKKNITHALTERNECKVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 3190,
      description:
        "This halterneck knitted evening dress is full length with a metal chain detail at the neckline and an open back. It features amber vintage gold metal hardware and is crafted from openwork stretch viscose with a gauge of 14, made up of 75% viscose and 25% polyester, offering a blend of transparency and stretch for a flattering fit.",
      stock: 15,
      category: "women",
    },
    {
      id: 28,
      name: "OPENWORK LUREX KNIT MAXI DRESS",
      mainImage: OPENWORKLUREX,
      subImages: [OPENWORKLUREX1],
      subVideos: [OPENWORKLUREXVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 2490,
      description:
        "This turtle-neck knitted maxi dress is ankle length and comes with a tonal detachable slip dress. It's crafted from openwork lurex with a gauge of 14, made up of 58% viscose, 27% polyester, 14% metallic fiber, and 1% nylon, offering a mix of sheen, softness, and durability.",
      stock: 15,
      category: "women",
    },
    {
      id: 29,
      name: "OPENWORK LUREX SCOOP NECK MAXI DRESS",
      mainImage: OPENWORKLUREXSCOOP,
      subImages: [OPENWORKLUREXSCOOP1],
      subVideos: [OPENWORKLUREXSCOOPVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 2490,
      description:
        "This scoop-neck knitted maxi dress is ankle length and features a tonal detachable slip dress. It includes a mother of pearl button and is crafted from openwork lurex with a gauge of 14, made up of 57% viscose, 28% polyester, and 15% metallic fibers, offering a blend of softness, shine, and durability.",
      stock: 15,
      category: "women",
    },
    {
      id: 30,
      name: "OPENWORK STRETCH VISCOSE KNIT MINI DRESS",
      mainImage: OPENWORKSTRETCHVISCOSE,
      subImages: [OPENWORKSTRETCHVISCOSE1],
      subVideos: [OPENWORKSTRETCHVISCOSEVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 1990,
      description:
        "This square-neck knitted mini dress features an Ottoman rib detail along the neckline and comes with a tonal detachable slip dress. It's crafted from openwork stretch viscose with a gauge of 14, made up of 70% viscose, 24% polyester, and 6% nylon, offering a mix of stretch, softness, and a slight sheen.",
      stock: 15,
      category: "women",
    },
    {
      id: 31,
      name: "OPENWORK STRETCH VISCOSE MAXI DRESS",
      mainImage: OPENWORKMAXIDRESS,
      subImages: [OPENWORKMAXIDRESS1, OPENWORKMAXIDRESS2],
      subVideos: [],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 2290,
      description:
        "This turtle-neck knitted maxi dress is ankle length and includes a tonal detachable slip dress. It's crafted from openwork stretch viscose with a gauge of 14, made up of 75% viscose and 25% polyester, offering a blend of softness, stretch, and a slight sheen.",
      stock: 15,
      category: "women",
    },
    {
      id: 32,
      name: "SABLE' HALTER NECK EVENING DRESS",
      mainImage: SABLEHALTERNECK,
      subImages: [SABLEHALTERNECK1],
      subVideos: [],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 5890,
      description:
        "This halter neck evening dress is full length, featuring a neckline patent leather construction with Hera hardware detail, a front deep side slit, and an open back. It includes an invisible zip and is finished with amber vintage gold metal hardware. Fully lined for comfort and structure, it's crafted from stretch sable', made up of 97% viscose and 3% elastane, offering a luxurious sheen and soft, flexible fit.",
      stock: 15,
      category: "women",
    },
    {
      id: 33,
      name: "SILK CREPE CHIFFON KAFTAN",
      mainImage: SILKCREPECHIFFON,
      subImages: [SILKCREPECHIFFON1],
      subVideos: [SILKCREPECHIFFONVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 6490,
      description:
        "A full-length kaftan featuring a crewneck with a drop opening, maxi batwing sleeves, sheer sleeves and sides, crafted from 94% silk and 6% elastane silk crepe chiffon fabric.",
      stock: 15,
      category: "women",
    },
    {
      id: 34,
      name: "SLINKY VISCOSE JERSEY KNIT MAXI DRESS",
      mainImage: SLINKYVISCOSEJERSEY,
      subImages: [SLINKYVISCOSEJERSEY1],
      subVideos: [SLINKYVISCOSEJERSEYVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 1890,
      description:
        "A turtle-neck knitted maxi dress with ankle length, shoulder pads, an invisible zip on the side, crafted from slinky viscose jersey with a gauge of 14, made entirely of 100% viscose.",
      stock: 15,
      category: "women",
    },
    {
      id: 35,
      name: "STRETCH SABLE' STRAPLESS EVENING DRESS",
      mainImage: STRETCHSABLESTRAPLESS,
      subImages: [STRETCHSABLESTRAPLESS1],
      subVideos: [STRETCHSABLESTRAPLESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 5590,
      description:
        "A strapless evening dress with full length, chest patent leather belt construction with logoed buckle, front deep side slit, invisible zip, gold metal hardware, fully lined, crafted in double stretch sable with 97% viscose and 3% elastane, with a detail of 100% calf leather.",
      stock: 15,
      category: "women",
    },
    {
      id: 36,
      name: "VELVET STRAPLESS EVENING DRESS",
      mainImage: VELVETSTRAPLESS,
      subImages: [VELVETSTRAPLESS1],
      subVideos: [VELVETSTRAPLESSVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 5980,
      description:
        "Inspired by an archive piece from Tom Ford FW11 main collection, a full-length evening dress that is strapless with a center V-shape neckline, featuring a powermesh internal bustier, fine satin tonal trim detail, an invisible zip at the center back, a center back deep slit, fully lined, with an internal Tom Ford archive label, crafted in viscose velvet with 69% viscose and 31% cupro.",
      stock: 15,
      category: "women",
    },
    {
      id: 37,
      name: "WOOL BLEND TWEED MINI COCKTAIL DRESS",
      mainImage: WOOLBLENDTWEED,
      subImages: [WOOLBLENDTWEED1],
      subVideos: [WOOLBLENDTWEEDVid],
      sizes: [34, 36, 38, 40, 42],
      colors: ["black", "champaigne"],
      type: "dresses",
      price: 4290,
      description:
        "The mini cocktail dress features a stand collar with a drop opening, cap sleeves, and front patch pockets, adorned with stitching detailing for a refined look. It includes an invisible zip at the center back for easy wear and is fully lined for structure and warmth. Crafted from a wool blend tweed, it comprises 65% nylon and 35% metalized polyester, blending durability with a glossy finish for a glamorous touch.",
      stock: 15,
      category: "women",
    },
    // Add more products as needed
  ],
  Kids: [
    {
      id: 7,
      name: "Kids' T-Shirt",
      mainImage: "path/to/main-image.jpg",
      subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
      sizes: ["XS", "S", "M", "L"],
      type: "t-shirt",
      price: 19.99,
      description: "A fun and colorful t-shirt for kids.",
      category: "Kids",
      stock: 25,
    },
    {
      id: 8,
      name: "Kids' Sneakers",
      mainImage: "path/to/main-image.jpg",
      subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
      sizes: [1, 2, 3, 4, 5],
      type: "shoes",
      price: 29.99,
      description: "Comfortable sneakers for active kids.",
      category: "Kids",
      stock: 30,
    },
    // Add more products as needed
  ],
};

export { products };

// const imagePath = (folder, name) => `/src/assets/${folder}/${name}`;

// const products = {
//   newArrivals: [
//     {
//       id: 1,
//       name: "Air Jordan 13 Retro 'Dune Red'",
//       mainImage: imagePath("New Arrivals", "Air Jordan 13 Retro Dune Red.jfif"),
//       subImages: [
//         imagePath("New Arrivals", "Air Jordan 13 Retro Dune Red 1.png"),
//         imagePath("New Arrivals", "Air Jordan 13 Retro Dune Red 2.jfif"),
//         imagePath("New Arrivals", "Air Jordan 13 Retro Dune Red 3.png"),
//       ],
//       sizes: [8, 9, 10, 11, 12],
//       type: "shoes",
//       price: 200,
//       description:
//         "The Air Jordan 13 Retro brings back the stealthy, shrouded design with a fresh mix of colors and textures. Crafted to the '98 specs as designed by Tinker Hatfield, you're getting the panther paw outsole, the holographic eye, and everything else that made these kicks iconic in the first place. MJ rode the original AJ13 all the way to his 6th ring—how are you gonna make this edition famous?",
//       category: "men",
//       stock: 10,
//     },
//     {
//       id: 2,
//       name: "Jordan Spizike Low",
//       mainImage: imagePath("New Arrivals", "Jordan Spizike Low.png"),
//       subImages: [
//         imagePath("New Arrivals", "Jordan Spizike Low 2.png"),
//         imagePath("New Arrivals", "Jordan Spizike Low 3.png"),
//         imagePath("New Arrivals", "Jordan Spizike Low 4.png"),
//       ],
//       sizes: [8, 9, 10, 11, 12],
//       type: "shoes",
//       price: 160,
//       description:
//         "The Spizike takes elements of five classic Jordans, combines them, and gives you one iconic sneaker. It's an homage to Spike Lee formally introducing Hollywood and hoops in a culture moment. You get a great looking pair of kicks with some history. What more can you ask for? Ya dig?",
//       category: "men",
//       stock: 10,
//     },
//     {
//       id: 3,
//       name: "JoAir Jordan 4 Retro 'Oxidized Green'",
//       mainImage: imagePath(
//         "New Arrivals",
//         "Air Jordan 4 Retro Oxidized Green.jfif",
//       ),
//       subImages: [
//         imagePath("New Arrivals", "Air Jordan 4 Retro Oxidized Green 1.png"),
//         imagePath("New Arrivals", "Air Jordan 4 Retro Oxidized Green 2.jfif"),
//         imagePath("New Arrivals", "Air Jordan 4 Retro Oxidized Green 3.png"),
//       ],
//       sizes: [8, 9, 10, 11, 12],
//       type: "shoes",
//       price: 215,
//       description:
//         "Step into a classic. This AJ4 throws it back with full-grain and synthetic leathers and premium textiles. Lush colors and metallic pops update the icon, while original design elements—like floating eyestays and mesh-inspired accents—feel just as fresh as they did in '89.",
//       category: "men",
//       stock: 10,
//     },
//     {
//       id: 4,
//       name: `Air Jordan 6 Retro "White/Black"`,
//       mainImage: imagePath(
//         "New Arrivals",
//         "Air Jordan 6 Retro White and Black.png",
//       ),
//       subImages: [
//         imagePath("New Arrivals", "Air Jordan 6 Retro White and Black 1.png"),
//         imagePath("New Arrivals", "Air Jordan 6 Retro White and Black 2.png"),
//         imagePath("New Arrivals", "Air Jordan 6 Retro White and Black 3.png"),
//       ],
//       sizes: [8, 9, 10, 11, 12],
//       type: "shoes",
//       price: 200,
//       description:
//         "MJ wore 'em when he claimed his first championship and you'll be wearing 'em for—well, whatever you want. Laden with dynamic design lines and those iconic lace locks, these sneakers bring throwback style to any 'fit. Lace up, and let your kicks do the talking.",
//       stock: 10,
//     },
//     {
//       id: 5,
//       name: `Air Jordan 1 Mid`,
//       mainImage: imagePath("New Arrivals", "Air Jordan 1 Mid.png"),
//       subImages: [
//         imagePath("New Arrivals", "Air Jordan 1 Mid 1.png"),
//         imagePath("New Arrivals", "Air Jordan 1 Mid 2.png"),
//         imagePath("New Arrivals", "Air Jordan 1 Mid 3.png"),
//       ],
//       sizes: [8, 9, 10, 11, 12],
//       type: "shoes",
//       price: 110,
//       description:
//         "This iteration of the AJ1 reimagines Mike's first signature model with a fresh mix of colors. Premium materials, soft cushioning and a padded ankle collar offer total support and celebrate the shoe that started it all.",
//       stock: 10,
//     },
//     {
//       id: 6,
//       name: "VISCOSE SATIN STRETCH JERSEY KAFTAN",
//       mainImage: imagePath(
//         "New Arrivals",
//         "VISCOSE SATIN STRETCH JERSEY KAFTAN.jfif",
//       ),
//       subImages: [
//         imagePath("New Arrivals", "VISCOSE SATIN STRETCH JERSEY KAFTAN 2.jfif"),
//         imagePath("New Arrivals", "VISCOSE SATIN STRETCH JERSEY KAFTAN.mp4"),
//       ],
//       sizes: [34, 36, 38, 40, 42],
//       type: "dress",
//       price: 4790,
//       description: "",
//       category: "women",
//       stock: 15,
//     },

//     {
//       id: 7,
//       name: "SATIN STRETCH JERSEY DEEP V-NECK KAFTAN",
//       mainImage: imagePath(
//         "New Arrivals",
//         "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS.jfif",
//       ),
//       subImages: [
//         imagePath(
//           "New Arrivals",
//           "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS 1.jfif",
//         ),
//         imagePath(
//           "New Arrivals",
//           "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS.mp4",
//         ),
//       ],
//       sizes: [34, 36, 38, 40, 42],
//       type: "dress",
//       price: 4790,
//       description: "",
//       category: "women",
//       stock: 15,
//     },
//     {
//       id: 8,
//       name: "SOFT SILK STRETCH CADY KAFTAN",
//       mainImage: imagePath(
//         "New Arrivals",
//         "SOFT SILK STRETCH CADY KAFTAN.jfif",
//       ),
//       subImages: [
//         imagePath("New Arrivals", "SOFT SILK STRETCH CADY KAFTAN 2.jfif"),
//         imagePath("New Arrivals", "SOFT SILK STRETCH CADY KAFTAN.mp4"),
//       ],
//       sizes: [34, 36, 38, 40, 42],
//       type: "dress",
//       price: 5290,
//       description: "",
//       category: "women",
//       stock: 15,
//     },
//     {
//       id: 9,
//       name: "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS",
//       mainImage: imagePath(
//         "New Arrivals",
//         "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS.jfif",
//       ),
//       subImages: [
//         imagePath(
//           "New Arrivals",
//           "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS 1.jfif",
//         ),
//         imagePath(
//           "New Arrivals",
//           "KNITTED STRETCH JERSEY CRISS-CROSS EVENING DRESS.mp4",
//         ),
//       ],
//       sizes: [34, 36, 38, 40, 42],
//       type: "dress",
//       price: 4590,
//       description: "",
//       category: "women",
//       stock: 15,
//     },
//     {
//       id: 10,
//       name: "CURLY SHEARLING JACKET",
//       mainImage: imagePath("New Arrivals", "CURLY SHEARLING JACKET.jfif"),
//       subImages: [
//         imagePath("New Arrivals", "CURLY SHEARLING JACKET 2.jfif"),
//         imagePath("New Arrivals", "CURLY SHEARLING JACKET.mp4"),
//       ],
//       sizes: [34, 36, 38, 40, 42],
//       type: "jacket",
//       price: 4980,
//       description: "",
//       category: "women",
//       stock: 15,
//     },
//     {
//       id: 11,
//       name: "CURLY SHEARLING JACKET",
//       mainImage: imagePath("New Arrivals", "CURLY SHEARLING JACKET.jfif"),
//       subImages: [
//         imagePath("New Arrivals", "CURLY SHEARLING JACKET 2.jfif"),
//         imagePath("New Arrivals", "CURLY SHEARLING JACKET.mp4"),
//       ],
//       sizes: [34, 36, 38, 40, 42],
//       type: "jacket",
//       price: 6890,
//       description: "",
//       category: "women",
//       stock: 15,
//     },
//     {
//       id: 12,
//       name: "GRAIN LEATHER TARA MEDIUM CROSSBODY",
//       mainImage: imagePath(
//         "New Arrivals",
//         "GRAIN LEATHER TARA MEDIUM CROSSBODY.jfif",
//       ),
//       subImages: [
//         imagePath("New Arrivals", "GRAIN LEATHER TARA MEDIUM CROSSBODY 2.jfif"),
//         imagePath("New Arrivals", "GRAIN LEATHER TARA MEDIUM CROSSBODY.mp4"),
//       ],
//       sizes: [], // Assuming no sizes are specified
//       type: "bag",
//       price: 2290,
//       description: "",
//       category: "women",
//       stock: 15,
//     },

//     // Add more products as needed
//   ],
//   Men: [
//     {
//       id: 3,
//       name: "Men's Suit",
//       mainImage: "path/to/main-image.jpg",
//       subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
//       sizes: ["M", "L", "XL", "XXL"],
//       type: "suit",
//       price: 199.99,
//       description: "A sleek and modern suit for formal occasions.",
//       category: "Men",
//       stock: 5,
//     },
//     {
//       id: 4,
//       name: "Men's Running Shoes",
//       mainImage: "path/to/main-image.jpg",
//       subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
//       sizes: [8, 9, 10, 11, 12],
//       type: "shoes",
//       price: 79.99,
//       description: "Lightweight and durable running shoes.",
//       category: "Men",
//       stock: 20,
//     },
//     // Add more products as needed
//   ],
//   Women: [
//     {
//       id: 5,
//       name: "Women's Knit Sweater",
//       mainImage: "path/to/main-image.jpg",
//       subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
//       sizes: ["S", "M", "L", "XL"],
//       type: "sweater",
//       price: 49.99,
//       description: "A cozy knit sweater for chilly days.",
//       category: "Women",
//       stock: 12,
//     },
//     {
//       id: 6,
//       name: "Women's High Heels",
//       mainImage: "path/to/main-image.jpg",
//       subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
//       sizes: [6, 7, 8, 9, 10],
//       type: "shoes",
//       price: 69.99,
//       description: "Elegant high heels for special occasions.",
//       category: "Women",
//       stock: 8,
//     },
//     // Add more products as needed
//   ],
//   Kids: [
//     {
//       id: 7,
//       name: "Kids' T-Shirt",
//       mainImage: "path/to/main-image.jpg",
//       subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
//       sizes: ["XS", "S", "M", "L"],
//       type: "t-shirt",
//       price: 19.99,
//       description: "A fun and colorful t-shirt for kids.",
//       category: "Kids",
//       stock: 25,
//     },
//     {
//       id: 8,
//       name: "Kids' Sneakers",
//       mainImage: "path/to/main-image.jpg",
//       subImages: ["path/to/sub-image1.jpg", "path/to/sub-image2.jpg"],
//       sizes: [1, 2, 3, 4, 5],
//       type: "shoes",
//       price: 29.99,
//       description: "Comfortable sneakers for active kids.",
//       category: "Kids",
//       stock: 30,
//     },
//     // Add more products as needed
//   ],
// };

// export default products;
